/*
** Made by texane <texane@gmail.com>
** 
** Started on  Wed Apr 15 22:58:54 2009 texane
** Last update Wed Apr 15 22:58:55 2009 texane
*/



#ifndef DIOT_COM_H_INCLUDED
# define DIOT_COM_H_INCLUDED



#ifdef DIOT_BUILD_SYS
# include <wdm.h>
#else
# include <winioctl.h>
#endif



#define DIOT_DEVICE_NAME L"diot"

#define DIOT_IOCTL_CODE(N) CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901 + N, METHOD_NEITHER, FILE_ANY_ACCESS)

#define DIOT_IOCTL_SET_USER_EVENT DIOT_IOCTL_CODE(0)

#define DIOT_IOCTL_GET_EVENTS DIOT_IOCTL_CODE(1)

#define DIOT_IOCTL_SET_CONF DIOT_IOCTL_CODE(2)
#define DIOT_IOCTL_GET_CONF DIOT_IOCTL_CODE(3)

#define DIOT_IOCTL_SET_MMIO_RANGES DIOT_IOCTL_CODE(4)
#define DIOT_IOCTL_GET_MMIO_RANGES DIOT_IOCTL_CODE(5)

#define DIOT_IOCTL_SET_IOPORT_RANGES DIOT_IOCTL_CODE(6)
#define DIOT_IOCTL_GET_IOPORT_RANGES DIOT_IOCTL_CODE(7)

#define DIOT_IOCTL_START_TRACING DIOT_IOCTL_CODE(8)
#define DIOT_IOCTL_STOP_TRACING DIOT_IOCTL_CODE(9)



#endif /* ! DIOT_COM_H_INCLUDED */
